app-text/stardict: disable festival and gpe, it's broken, fail to compile
1) festival fail to compile, missing header file

2) gpe fail to compile,
prefsdlg.cpp:1524:27: error: no 'void PrefsDlg::find_skins()' member fu[63/1906]
clared in class 'PrefsDlg'
 void PrefsDlg::find_skins()

prefsdlg.cpp: In member function 'void PrefsDlg::setup_mainwin_options_page()':
prefsdlg.cpp:1602:13: error: 'find_skins' was not declared in this scope
			      find_skins();
			                   ^


Signed-off-by: Lan Yixun (dlan) <dennis.yxun@gmail.com>